name: hlmobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dio: ^5.4.0
  sqflite: ^2.2.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  path: ^1.8.2
  image_picker: ^0.8.4+4
  intl: ^0.19.0
  file_picker: ^5.5.0
  lottie: ^2.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
